from pathlib import Path

import ghstack_tui.config as config_mod
from ghstack_tui.config import (
    AppConfig,
    DEFAULT_CONFIG_PATH,
    ensure_default_config_file,
    get_config,
    load_config,
    render_default_config,
    reset_config_cache,
)


def test_load_config_defaults_when_file_missing(tmp_path):
    config = load_config(tmp_path / "missing.toml")

    assert isinstance(config, AppConfig)
    assert config.paths.default_checkout_path == "~/git/pytorch313"
    assert config.search.default_query == "is:pr is:open author:@me"
    assert config.agents.pi_command == "pi"


def test_load_config_merges_overrides(tmp_path):
    path = tmp_path / "config.toml"
    path.write_text(
        """
[paths]
default_checkout_path = "~/git/custom"

[search]
clones_prefix = "torch"

[agents]
pi_command = "pi-custom"

[prompts]
pi_initial_task = "Do the thing."
""".strip()
    )

    config = load_config(path)

    assert config.paths.default_checkout_path == "~/git/custom"
    assert config.paths.clones_root == "~/git"
    assert config.search.clones_prefix == "torch"
    assert config.agents.pi_command == "pi-custom"
    assert config.prompts.pi_initial_task == "Do the thing."


def test_get_config_uses_env_override(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    path.write_text('[agents]\nclaude_command = "my-claude"\n')
    monkeypatch.setenv("GHSTACK_TUI_CONFIG", str(path))
    reset_config_cache()

    try:
        config = get_config()
    finally:
        reset_config_cache()
        monkeypatch.delenv("GHSTACK_TUI_CONFIG", raising=False)

    assert config.agents.claude_command == "my-claude"


def test_default_config_path_points_to_user_config_dir():
    assert DEFAULT_CONFIG_PATH == Path.home() / ".config" / "ghstack-tui" / "config.toml"


def test_render_default_config_contains_sections():
    text = render_default_config()

    assert "[paths]" in text
    assert "[search]" in text
    assert "[agents]" in text
    assert "[prompts]" in text


def test_ensure_default_config_file_creates_starter_config(tmp_path):
    path = tmp_path / "ghstack-tui.toml"

    created = ensure_default_config_file(path)

    assert created == path
    assert path.is_file()
    text = path.read_text()
    assert "# Auto-generated by ghstack-tui on first run." in text
    assert 'default_checkout_path = "~/git/pytorch313"' in text


def test_load_config_with_explicit_path_does_not_auto_create_file(tmp_path):
    path = tmp_path / "config.toml"

    config = load_config(path)

    assert config.paths.default_checkout_path == "~/git/pytorch313"
    assert path.is_file() is False


def test_load_config_auto_creates_default_file(monkeypatch, tmp_path):
    path = tmp_path / "config.toml"
    monkeypatch.setattr(config_mod, "DEFAULT_CONFIG_PATH", path)
    monkeypatch.delenv("GHSTACK_TUI_CONFIG", raising=False)
    reset_config_cache()

    try:
        config = load_config()
    finally:
        reset_config_cache()

    assert config.paths.default_checkout_path == "~/git/pytorch313"
    assert path.is_file()
