from __future__ import annotations

import importlib.resources
import os
import tomllib
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any


DEFAULT_CONFIG_PATH = Path.home() / ".config" / "ghstack-tui" / "config.toml"
_CONFIG_ENV_VAR = "GHSTACK_TUI_CONFIG"


@dataclass(frozen=True)
class PathsConfig:
    default_checkout_path: str
    clones_root: str
    triage_cache_path: str
    mcp_config_dir: str


@dataclass(frozen=True)
class SearchConfig:
    default_query: str
    clones_prefix: str
    gh_search_limit: int


@dataclass(frozen=True)
class AgentsConfig:
    claude_command: str
    pi_command: str


@dataclass(frozen=True)
class PromptsConfig:
    claude_fix_ci_template: str
    claude_review_template: str
    pi_intro: str
    pi_checkout_instruction: str
    pi_gh_instruction_template: str
    pi_validation_instruction: str
    pi_initial_task: str
    pi_fallback_task: str


@dataclass(frozen=True)
class AppConfig:
    paths: PathsConfig
    search: SearchConfig
    agents: AgentsConfig
    prompts: PromptsConfig


def _load_bundled_config() -> dict[str, Any]:
    data = importlib.resources.files("ghstack_tui").joinpath("config.toml").read_bytes()
    return tomllib.loads(data.decode())


def _merge_dicts(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    out = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _merge_dicts(out[key], value)
        else:
            out[key] = value
    return out


def _config_from_dict(data: dict[str, Any]) -> AppConfig:
    paths = PathsConfig(**data["paths"])
    search = SearchConfig(**data["search"])
    agents = AgentsConfig(**data["agents"])
    prompts = PromptsConfig(**data["prompts"])
    return AppConfig(paths=paths, search=search, agents=agents, prompts=prompts)


def render_default_config() -> str:
    raw = importlib.resources.files("ghstack_tui").joinpath("config.toml").read_text(encoding="utf-8")
    header = "# Auto-generated by ghstack-tui on first run.\n# Edit any of these values to customize local defaults.\n\n"
    return header + raw


def ensure_default_config_file(path: str | Path | None = None) -> Path:
    config_path = Path(path).expanduser() if path is not None else DEFAULT_CONFIG_PATH
    if config_path.exists():
        return config_path
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(render_default_config())
    return config_path


def load_config(path: str | Path | None = None) -> AppConfig:
    if path is not None:
        config_path = Path(path).expanduser()
    else:
        config_path = _resolve_config_path()
        if os.environ.get(_CONFIG_ENV_VAR) is None:
            ensure_default_config_file(config_path)
    defaults = _load_bundled_config()
    if not config_path.is_file():
        return _config_from_dict(defaults)
    with config_path.open("rb") as f:
        raw = tomllib.load(f)
    merged = _merge_dicts(defaults, raw)
    return _config_from_dict(merged)


def _resolve_config_path() -> Path:
    override = os.environ.get(_CONFIG_ENV_VAR)
    if override:
        return Path(override).expanduser()
    return DEFAULT_CONFIG_PATH


@lru_cache(maxsize=1)
def get_config() -> AppConfig:
    return load_config()


def reset_config_cache() -> None:
    get_config.cache_clear()
